apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: karpenter-dev
      env: dev

resources:
  - manifests/ec2_node_class.yml
  - manifests/node_pool_t.yml
  - manifests/node_pool_mcr.yml